[package]
name = "pal"
version = "0.1.0"
authors = ["Saghm Rossi <saghmrossi@gmail.com>"]
license = "MIT"
build = "build.rs"

[build-dependencies]
lalrpop = "0.12"

[dependencies]
lalrpop-util = "0.12"
rl-sys = "0.5"
stepper = "0.1"
unicode-xid = "0.0.3"
